### ISSUE TITLE
font-awesome dependency? fb icon doesn't work

### ISSUE THREAD

**Issue by rstormsf** [fortitude/fortitude-sass#58]
I've seen http://hired.com/library makes a request to fetch font-awesome lib for icons, but some still not working

<img width="1290" alt="fortitude_library___hired" src="https://cloud.githubusercontent.com/assets/9360827/9149249/08c243c2-3d56-11e5-8ea3-69daa296d6e5.png">

**Comment by lifeiscontent** [comment]
@rstormsf thanks a lot for your issues! It's really appreciated.

So that icon in particular is custom, we unfortunately use both font-awesome and a custom icon set. (from previous architecture)

the icon you're pointing out though just happens to be white, which is why its invisible. We're in the middle of a rewrite of the styleguide now and should be finished later sometime this week. :smile:

**Comment by lifeiscontent** [comment]
@rstormsf we've made updates! https://hired.com/library

**Comment by rstormsf** [comment]
this is waaaay better. Thank you!
